### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by hroncok** [ziima/televize#2]
Hi,

could you please do a PyPI release, so I can just `pip install televize`?

(Also, I'd like to package this for Fedora (maybe RPM Fusion), hence, I'd very much appreciate if the tests and LICENSE would be in the release tarball.)

Thanks.

**Comment by ziima** [comment]
Ad PyPI: OK, I'll try to publish it.
Ad fedora: Can you provide patch for setup.py?

**Comment by hroncok** [comment]
Will do.

**Comment by ziima** [comment]
I think I was able to do it.

Anyway televize is on pypi.

**Comment by hroncok** [comment]
Done in e494539405875b0bde85bf1b95b2ed3d20d6e4fd
