### ISSUE TITLE
Video resolution

### ISSUE THREAD

**Issue by hroncok** [ziima/televize#7]
When I play a video from ivysilani, I get it in 512x288 resolution, while on the website, I can go full HD. Any way how do I choose a resolution? The `--help` messages are not quite usefull here so I guess either is not yet currently possible or I have to use some mpv options. ...? Thanks for help.

**Comment by ziima** [comment]
It's not yet implemented. I run on the lowest resolution, so it didn't bother me much. But also I couldn't propose any reasonable way to select it. I'd like to have it user-friendly, but ČT doesn't make it easy.

Variants can be chosen by bandwidth, which contain weird values (500000, 1032000, 2048000, 3584000) and these values are, as I remember, not the same for every stream. So the simple option `--bandwidth=VALUE` wouldn't probably be very useful.

Alternative is probably something like `--quality`, but I fail to propose a reasonable values for it. Integers (1 - lowest, 4 - highest)? Strings (low, high)? Combination?

Any ideas?

**Comment by hroncok** [comment]
Well, either start with `--list-bandwidths` and `--bandwith=` and make it not very user friendly, but at least deterministic.

Or, add some `--quality` scale. That would probably require some knowledge about the badnwidths I don't yet have, so in order to come with a proposed solution, let me make some assertions and correct me if I'm wrong:

 * there are `>= 1` bandwidth options, but we don't know how many (can vary depending on stream), but the number is reasonably small
 * the number somehow correlates with the resolution (i.e. the higher bandwidth, the higher the resolution or the other way around)

If this is the case, I'd go with:

 * `--quality=0` picks the lowest possible bandwidth
 * `--quality=1` picks the second lowest possible bandwidth
 * `--quality=2` ...
 * `--quality=-1` picks the highest possible bandwidth
 * `--quality=-2` picks the second highest possible bandwidth
 * `--quality=-3` ...
* `--quality=best` as an alias to `-1`
* `--quality=worst` as an alias to `0`

If the user selects a unreachable value (such as 3 when there are only 3 options), the closest possible value is selected (possibly with a warning)

**Comment by ziima** [comment]
`--quality` implemented in #9. I went with keywords `min` and `max` and an error if invalid quality is provided.

In my experience, there are always 4 bandwidths available, so number 0 to 3 should be enough.

Further comment are welcome, otherwise enjoy Olympics (to be tagged tomorrow).
